// --------------------------------------------------------------------------------------------------------------------
// <copyright company="" file="Site.Master.designer.cs">
//   
// </copyright>
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
// <summary>
//   The site master.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace SE2StackOverflow {
    using System.Web.UI.WebControls;

    /// <summary>
    /// The site master.
    /// </summary>
    public partial class SiteMaster {
        

        /// <summary>
        /// TextBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected TextBox TextBox1;
        

        /// <summary>
        /// MainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected ContentPlaceHolder MainContent;
        

        /// <summary>
        /// Error control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected Label Error;
    }
}
