// --------------------------------------------------------------------------------------------------------------------
// <copyright company="" file="ViewSwitcher.ascx.designer.cs">
//   
// </copyright>
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
// <summary>
//   The view switcher.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace SE2StackOverflow {
    /// <summary>
    /// The view switcher.
    /// </summary>
    public partial class ViewSwitcher {
    }
}
